GRE_WORDS = [
    "abate", "abdicate", "aberrant", "abjure", "abscond", "abstemious", "admonish", "adulterate", "aesthetic",
    "aggrandize", "alacrity", "ambiguous", "ameliorate", "anachronism", "analogous", "anomalous", "antipathy",
    "apathy", "appease", "arbitrary", "arcane", "arduous", "artless", "ascetic", "assiduous", "attenuate",
    "audacious", "austere", "aver", "banal", "belie", "beneficent", "bolster", "bombastic", "brazen", "burgeon",
    "burnish", "buttress", "cacophony", "candid", "capricious", "castigate", "catalyst", "caustic", "censure",
    "chicanery", "coagulate", "cogent", "commensurate", "compendium", "complacent", "complaisant", "connoisseur",
    "contentious", "contrite", "conundrum", "convoluted", "craven", "daunt", "deference", "denigrate", "deride",
    "derivative", "desiccate", "desultory", "deterrent", "diatribe", "dichotomy", "diffidence", "diffuse",
    "digression", "dirge", "disabuse", "discerning", "discordant", "discredit", "discrepancy", "disingenuous",
    "disinterested", "disjointed", "dismiss", "disparage", "disparate", "dissemble", "dissonance", "distend",
    "divest", "document", "dogmatic", "dormant", "dupe", "ebullient", "eclectic", "efficacy", "effrontery",
    "elicit", "embellish", "empirical", "emulate", "enervate", "engender", "enhance", "enigma", "ephemeral",
    "equanimity", "equivocate", "erudite", "esoteric", "estimable", "eulogy", "euphemism", "exacerbate",
    "exculpate", "exigency", "exonerate", "expatiate", "expedient", "explicit", "extrapolation", "facetious",
    "fallacious", "fatuous", "fawning", "felicitous", "fervor", "flag", "fledgling", "flout", "foment",
    "forestall", "foster", "frugality", "gainsay", "garrulous", "goad", "gouge", "grandiloquent", "gregarious",
    "guileless", "gullible", "harangue", "harry", "heterodox", "hierarchy", "homogeneous", "hyperbole",
    "iconoclast", "idolatry", "immutable", "impair", "impassive", "impecunious", "impede", "impermeable",
    "imperturbable", "impervious", "impetuous", "impugned", "inadvertently", "inchoate", "incipient",
    "indigence", "indolent", "inefficacious", "inert", "ingenuous", "inherent", "innocuous", "insensible",
    "insinuate", "insipid", "insular", "insuperable", "interdict", "intractable", "intransigence", "intrepid",
    "inundate", "inured", "invective", "irascible", "irresolute", "itinerant", "jettison", "jocular", "laconic",
    "lethargic", "limpid", "loquacious", "lucid", "luminous", "magnanimity", "malevolent", "malinger", "malleable",
    "maverick", "mendacious", "metamorphosis", "meticulous", "misanthrope", "mitigate", "mollify", "morose",
    "mundane", "neophyte", "obdurate", "obsequious", "obstinate", "obviate", "occlude", "officious", "onerous",
    "opprobrium", "oscillate", "ostentatious", "paragon", "partisan", "pathological", "paucity", "pedantic",
    "penchant", "penury", "perfunctory", "permeable", "pervasive", "phlegmatic", "piety", "placate", "plasticity",
    "platitude", "plethora", "pragmatic", "precipitate", "precursor", "presumptuous", "prevaricate", "probity",
    "prodigal", "profound", "prohibitive", "proliferate", "prologue", "propensity", "propitiate", "propriety",
    "proscribe", "provident", "pugnacious", "punctilious", "pusillanimous", "quiescent", "rarefy", "recalcitrant",
    "recant", "recondite", "refractory", "refute", "relegate", "reproach", "reprobate", "repudiate", "rescind",
    "reticent", "reverent", "rhetorical", "salubrious", "sanction", "satiate", "saturate", "secrete", "shard",
    "skeptic", "slake", "soporific", "specious", "sporadic", "stigma", "stint", "stipulate", "stolid", "strut",
    "subpoena", "subside", "substantiate", "supersede", "supine", "supplant", "suppress", "surreptitious",
    "sycophant", "tacit", "tangential", "tenuous", "tirade", "torpor", "tortuous", "tractable", "transgression",
    "truculence", "turbulent", "turgid", "vacillate", "veneration", "veracious", "verbose", "viable", "vigilant",
    "vilify", "viscous", "vituperative", "volatile", "wary", "welter", "whimsical", "zealot"
]
